dist: trusty

language: cpp

before_install:
  - sudo apt-get install wget pkg-config g++ zlib1g-dev openjdk-8-jdk
  - wget https://github.com/bazelbuild/bazel/releases/download/0.3.1/bazel_0.3.1-linux-x86_64.deb
  - sudo dpkg -i bazel_0.3.1-linux-x86_64.deb

script:
  - bazel test //src/test:m4-test