dist: xenial

language: generic

jdk: openjdk8
compiler: clang

before_install:
  - sudo apt-get install wget pkg-config g++ zlib1g-dev
  - wget https://github.com/bazelbuild/bazel/releases/download/0.24.1/bazel_0.24.1-linux-x86_64.deb
  - sudo dpkg -i bazel_0.24.1-linux-x86_64.deb

script:
  - bazel test //src/test:m4-test --test_output=all